version: "3.1"

services:
  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.CHANGEME.rule=Host(`example.domain.com`)"
      - "traefik.http.routers.CHANGEME.entrypoints=websecure"
      - "traefik.http.routers.CHANGEME.tls.certresolver=myresolver"
    networks:
      - dev
networks:
  dev:
    external: true
